### ISSUE TITLE
Trên devices thật không play được video

### ISSUE THREAD

**Issue by MaVuong** [MaVuong/TestCocosJS#51]

**Comment by haanhman** [comment]
vãi lỗi thật
![img_0356](https://cloud.githubusercontent.com/assets/6611502/24279154/b11a5c5a-107a-11e7-80a4-4bcef66c302d.PNG)

**Comment by haanhman** [comment]
cái này tao test lại ko thấy bị chết, chắc do mày chơi card a - d khi chưa có video
