### ISSUE TITLE
Tạo API yêu cầu show rate app khi app đã Approve trên appstore và gg

### ISSUE THREAD

**Issue by MaVuong** [MaVuong/TestCocosJS#63]

**Comment by haanhman** [comment]
@MaVuong 
http://54.218.122.252/api/index/rate

Xem thêm thông tin API tại đây nhé: [API](https://github.com/MaVuong/TestCocosJS/wiki/API#utils)

**Comment by haanhman** [comment]
ở trong file Utils tao có function để kiểm tra card nào rate app thì được down free

```
limitRateToUnlock: function () {
        if (cc.sys.localStorage.getItem('vkids_need_rate_app') == true) {
            return ['e'];
        }
        return [];
    }
```

Mày chỉ cần load cái API này về [http://54.218.122.252/api/index/rate](http://54.218.122.252/api/index/rate)

Nếu rate = 1 thì set biến vkids_need_rate_app = true là ok
