### ISSUE TITLE
Nhận diện ngôn ngữ máy iOS , android yêu cầu Rate khi nhấn chữ D

### ISSUE THREAD

**Issue by MaVuong** [MaVuong/TestCocosJS#64]

**Comment by haanhman** [comment]
Xem code ở file này nhé
https://github.com/MaVuong/TestCocosJS/blob/develop/assets/Script/Utils/Utils.js

```
limitFree: function () {
    return ['a', 'b', 'c', 'd'];
},
limitRateToUnlock: function () {
    if (cc.sys.localStorage.getItem('vkids_need_rate_app') == true) {
        return ['e'];
    }
return [];
},
```

tao có 2 hàm ở ngay trên đầu để xử lý card nào free, card nào cần rate mới unlock được

**Comment by haanhman** [comment]
còn cái popup yêu cầu rate 5 sao để unlock card D chưa làm

**Comment by haanhman** [comment]
tạm close bug này ko cần làm nữa, đã có popup rate rồi 
![rate_alert_demo](https://cloud.githubusercontent.com/assets/6611502/24834705/75ab97ca-1d17-11e7-8c2f-7be3090f47b6.png)
