### ISSUE TITLE
Nên làm game theo thứ tự , không random như hiện tại 

### ISSUE THREAD

**Issue by MaVuong** [MaVuong/TestCocosJS#65]
Đã thử làm game theo thứ tự nhưng cũng random tức là thay đổi thứ tự game nhưng ví dụ trace A,a viết liền một lúc , game touch the A 3 lần cùng 1 lúc cảm giác hơi nhàm chán , nên tao nghĩ mình vẫn để random ngẫu nhiên như trước

**Comment by haanhman** [comment]
ok vậy cứ để random như trước, tao sẽ bỏ qua phần pháo hoa ở 2 game word và game trace

chuyển nó xuống cuối cùng khi chơi xong hết các game

**Comment by haanhman** [comment]
game word tách 2 lần chơi ra để random như các game khác

**Comment by haanhman** [comment]
ok rồi
