### ISSUE TITLE
Chức Năng Download Card

### ISSUE THREAD

**Issue by MaVuong** [MaVuong/TestCocosJS#69]
-thêm popup mỗi khi nhấn download
-trong quá trình download card thì bắt nó chờ không được làm gì khác vì dữ liệu của mỗi card cũng không nhiều

**Comment by haanhman** [comment]
![img_0367 png](https://cloud.githubusercontent.com/assets/6611502/24576067/1d505b08-16df-11e7-8717-b23263526aa5.jpg)
