### ISSUE TITLE
Thêm button More Apps!

### ISSUE THREAD

**Issue by MaVuong** [MaVuong/TestCocosJS#70]
khi user họ mua xong bản fullversion thì bên button fullversion bị ẩn đi trông sẽ không đẹp mình nên thay thế bằng button more app vào đó , button more apps! đã thiết kế rồi

**Comment by haanhman** [comment]
![more_button_2](https://cloud.githubusercontent.com/assets/6611502/24586480/32a63c00-17cc-11e7-881f-66dcd6f949b3.gif)
