### ISSUE TITLE
Video Song  chưa che vạch trắng trên ipad nhìn thấy ngay 

### ISSUE THREAD

**Issue by MaVuong** [MaVuong/TestCocosJS#73]
![img_0897](https://cloud.githubusercontent.com/assets/5964485/24576517/60bcf43e-16e7-11e7-8337-e87ddb34ba44.PNG)

**Comment by haanhman** [comment]
design 1 cái logo rồi dùng affter effect thay vào

**Comment by haanhman** [comment]
đã upload lại toàn bộ nội dung card lên cả 4 server rồi
